<?php echo $this->doctype(); $auth = $this->identity(); ?>


<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Admin Panel</title>

        <meta name="author" content="LayoutIt!">

        <link href="/css/admin/bootstrap.min.css" rel="stylesheet">
        <link href="/css/admin/style.css" rel="stylesheet">

    </head>
    <body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                    <div class="navbar-header">

                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                        </button> <a class="navbar-brand" href="#">ZF2</a>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <?php if(!empty($auth)){ ?>
                        <ul class="nav navbar-nav">
                            <li><a href="<?=$this->url('admin/default', array('controller' => 'index'));?>">Main</a></li>

                            <!--li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'blog'));?>">Lise</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'blog', 'action' => 'add'));?>">Add article</a></li>
                                </ul>
                            </li-->

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'user'));?>">List</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'user', 'action' => 'add'));?>">Add user</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Orders<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'order'));?>">List</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 8));?>">Наши Обьекты</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 9));?>">О компании</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 10));?>">Поставщикам</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 11));?>">Услуги</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 12));?>">Акции</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 13));?>">Оплата</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 14));?>">Доставка</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 15));?>">Обратная связь</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 16));?>">Сервисный центр</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 17));?>">Гарантийное обслуживание</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 18));?>">Монтаж</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 19));?>">Проектирование</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 20));?>">Обслуживание</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 21));?>">Документация</a></li>
                                    <hr>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 23));?>">Кондиционирование</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 24));?>">Тепловое оборудование</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 25));?>">Камины</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 22));?>">Вентиляция</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 26));?>">Строительство</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'page', 'action' => 'edit', 'id' => 27));?>">Дизайн</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Catalog<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'product'));?>">list</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'product', 'action' => 'add'));?>">Add product</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'category'));?>">list</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'category', 'action' => 'add'));?>">Add category</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Album<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'album'));?>">list</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'album', 'action' => 'add'));?>">Add album</a></li>
                                </ul>
                            </li>

                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Comments<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'comment'));?>">List</a></li>
                                </ul>
                            </li> -->

                            <!--li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'sending-email'));?>">Sending E-Mail</a></li>
                                </ul>
                            </li-->

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">SEO<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 1));?>">Главная</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 2));?>">Авторизация</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 3));?>">Регистрация</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 4));?>">Восстановление пароля</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 5));?>">Поиск</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 6));?>">Корзина покупок</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 7));?>">Оформление заказа</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 8));?>">Наши Обьекты</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 9));?>">О компании</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 10));?>">Поставщикам</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 11));?>">Услуги</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 12));?>">Акции</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 13));?>">Оплата</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 14));?>">Доставка</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 15));?>">Обратная связь</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 16));?>">Сервисный центр</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 17));?>">Гарантийное обслуживание</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 18));?>">Монтаж</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 19));?>">Проектирование</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 20));?>">Обслуживание</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 21));?>">Документация</a></li>
                                    <!--hr>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 23));?>">Кондиционирование</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 24));?>">Тепловое оборудование</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 25));?>">Камины</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 22));?>">Вентиляция</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 26));?>">Строительство</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit', 'id' => 27));?>">Дизайн</a></li-->
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Setting<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'setting', 'action' => 'edit-currency', 'id' => 4));?>">RUB</a></li>
                                </ul>
                            </li>

                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Parser<strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'SHOWROOMPRIVE'));?>">SHOWROOMPRIVE <-- работа возможна только на мощном сервере или полуручной режим</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'piustyle'));?>">Piustyle</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'SARENZA'));?>">SARENZA <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'SPARTOO'));?>">SPARTOO <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'BAGALIER'));?>">BAGALIER <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'fratinardi'));?>">Fratinardi</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'GUTTERIDGE'));?>">GUTTERIDGE <-- если нужны все цвета то работа возможна только на мощном сервере или полуручной режим</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'FASCHIONETTE'));?>">FASCHIONETTE <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'FRMODA'));?>">FRMODA <-- раздел не найден----</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'CORSOROMA'));?>">CORSOROMA <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'SMARTBUYGLASSES'));?>">SMARTBUYGLASSES <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'STYLIGHT'));?>">STYLIGHT <-- адрес сайта не найден</a></li>
                                    <li><a href="<?=$this->url('admin/default', array('controller' => 'parser', 'action' => 'HAWKERSCO'));?>">HAWKERSCO <-- работа возможна только на мощном сервере или полуручной режим</a></li>
                                </ul>
                            </li> -->


                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <!--<a href="/<?=$lang_url?>/logout/">Logout</a>-->
                                <a href="<?=$this->url('auth/logout');?>">Logout</a>
                            </li>
                            <li>
                                <a href="#"></a>
                            </li>
                        </ul>
                        <?php } ?>
                    </div>

                </nav>
                <br><br><br><br>
                <div class="row">

                <?=$this->content; ?>

                </div>
            </div>
        </div>
    </div>

        <script src="/js/admin/jquery.min.js"></script>
        <script src="/js/admin/bootstrap.min.js"></script>
        <script src="/js/admin/scripts.js"></script>
    </body>
</html>