<div class="col-md-12">
    <form action="<?php echo $this->url('admin/default', array('controller' => 'blog', 'action' => 'add')) ?>" method="POST" enctype="multipart/form-data">
        <button type="submit" name="submit" class="btn btn-primary">
            Submit
        </button>
        <div class="form-group" >

            <input type="text" name="name" class="form-control" id="exampleInputText" maxlength="80" placeholder="Название" required>
        </div>
        <div class="form-group" >

            <input type="text" name="title" class="form-control" id="exampleInputText" maxlength="200" placeholder="Teg Title" required>
        </div>
        <div class="form-group" >

            <input type="text" name="keywords" class="form-control" id="exampleInputText" maxlength="250" placeholder="Teg Key words">
        </div>
        <div class="form-group" >

            <input type="text" name="description" class="form-control" id="exampleInputText" maxlength="200" placeholder="Teg Description">
        </div>
        <div class="form-group">

            <textarea name="text" class="form-control"></textarea>
        </div>
    </form>
</div>

<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace("text");
</script>
