<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<div class="col-md-12">
    <div id="save">
        <a href="<?php echo $this->url('admin/default', array('controller' => 'blog', 'action' => 'add'));?>" class="btn btn-success">Add</a>

    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>
                id
            </th>
            <th>
                Name
            </th>
            <th>
                Date
            </th>
            <th>
                Funct.
            </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($articles as $item){ ?>
            <tr class="active">
                <td style="width: 10px;">
                    <?php echo $item->getId() ?>
                </td>
                <td>
                    <?php echo $item->getName() ?>
                </td>
                <td>
                    <?php echo date("d.m.Y", $item->getDate()) ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'blog', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'blog', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php

    echo $this->paginationControl($articles,
        'Sliding',
        'pagination_control', array('route' => $this->url('admin/default', array('controller' => 'blog'))));

    ?>
</div>