<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>


<div class="bs-docs-section">
    <div class="well">


        <?php
        $form->setAttribute('action', $this->url('admin/default', array('controller' => 'setting', 'action' => 'edit-currency', 'id' => $id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo '<h1>Редактировать пользователя</h1>';
        foreach ($form as $element){
            echo '<div class="form-group">';
            $attributes = $element->getAttributes();

            if($element->getLabel()){
                $element->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
                if(isset($attributes['required'])){
                    $element->setLabel($element->getLabel() . ' *');
                }
            }

            if(isset($attributes['type']) && $attributes['type'] == 'text')
            {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formInput($element);
                echo '</div>';
            }
            elseif(isset($attributes['type']) && $attributes['type'] == 'textatea')
            {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formTextArea($element);
                echo '</div>';
            }
            elseif(isset($attributes['type']) && $attributes['type'] == 'file')
            {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formFile($element);
                echo '</div>';
            }
            elseif(isset($attributes['type']) && $attributes['type'] == 'email')
            {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formEmail($element);
                echo '</div>';
            }
            elseif(isset($attributes['type']) && $attributes['type'] == 'password')
            {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formPassword($element);
                echo '</div>';
            }
            elseif(isset($attributes['type']) && $attributes['type'] == 'select')
            {
                echo $this->formLabel($element);
                echo '<div class="col-lg-10">';
                echo $this->formSelect($element);
                echo '</div>';
            }
            else
            {
                echo '<div class="col-lg-10">';
                echo $this->formRow($element);
                echo '</div>';
            }

            echo '</div>';
        }
        //echo '</fieldset>';
        echo $this->form()->closeTag();
        ?>

    </div>
</div>
