<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<?php
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'album', 'action' => 'edit', 'id' => $album->getId())));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="col-md-12">
    <div class="tabbable" id="tabs-582967">
        <div style="min-height: 42px">
            <ul class="nav nav-tabs pull-left" style="margin-bottom: 10px">
                <li class="active">
                    <a href="#panel1" data-toggle="tab">Основное</a>
                </li>
                <li>
                    <a href="#panel2" data-toggle="tab">Доп. Фото</a>
                </li>
                <!-- <li>
                    <a href="#panel3" data-toggle="tab">English</a>
                </li>
                <li>
                    <a href="#panel4" data-toggle="tab">Italiano</a>
                </li>
                <li>
                    <a href="#panel5" data-toggle="tab">Русский</a>
                </li> -->


            </ul>

            <button class="pull-right btn btn-success">Сохранить</button>

        </div>
        <div class="tab-content">
            <div class="tab-pane active" id="panel1">
                <div class="bs-docs-section">
                    <div class="well">


                        <?php

                        echo '<h1>Редактировать продукт</h1>';
                        //echo $product->getUrl() != '' ? '<a href="'.$product->getUrl().'">Товар на сайте</a>' : '';
                        foreach ($form as $element){
                            echo '<div class="form-group">';
                            $attributes = $element->getAttributes();

                            if($element->getLabel()){
                                $element->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
                                if(isset($attributes['required'])){
                                    $element->setLabel($element->getLabel() . ' *');
                                }
                            }

                            if(isset($attributes['type']) && $attributes['type'] == 'text')
                            {
                                echo $this->formLabel($element);
                                echo '<div class="col-lg-10">';
                                echo $this->formInput($element);
                                echo '</div>';
                            }
                            elseif(isset($attributes['type']) && $attributes['type'] == 'textatea')
                            {
                                echo $this->formLabel($element);
                                echo '<div class="col-lg-10">';
                                echo $this->formTextArea($element);
                                echo '</div>';
                            }
                            elseif(isset($attributes['type']) && $attributes['type'] == 'file')
                            {
                                echo $this->formLabel($element);
                                echo '<div class="col-lg-10">';
                                echo '<img src="/uploads/album/'.$album->getPhoto().'" class="img-responsive img-product-228">';
                                echo $this->formFile($element);
                                echo '</div>';
                            }
                            elseif(isset($attributes['type']) && $attributes['type'] == 'email')
                            {
                                echo $this->formLabel($element);
                                echo '<div class="col-lg-10">';
                                echo $this->formEmail($element);
                                echo '</div>';
                            }
                            elseif(isset($attributes['type']) && $attributes['type'] == 'password')
                            {
                                echo $this->formLabel($element);
                                echo '<div class="col-lg-10">';
                                echo $this->formPassword($element);
                                echo '</div>';
                            }
                            elseif(isset($attributes['type']) && $attributes['type'] == 'select')
                            {
                                echo $this->formLabel($element);
                                echo '<div class="col-lg-10">';
                                echo $this->formSelect($element);
                                echo '</div>';
                            }
                            else
                            {
                                echo '<div class="col-lg-10">';
                                echo $this->formRow($element);
                                echo '</div>';
                            }

                            echo '</div>';
                        }
                        //echo '</fieldset>';

                        ?>

                    </div>
                </div>
            </div>
            <div class="tab-pane" id="panel2">
                <div class="bs-docs-section">
                    <div class="well">
                        <?php foreach($album_image as $item){
                            echo '<img src="/uploads/album/'.$item->getUrl().'" id="'.$item->getId().'" onclick="dellImg('.$item->getId().')" style="width: 100px">';
                        } ?>
                        <hr>
                        <div class="form-group">
                            <label class="col-lg-2 control-label" for="photoAll">Дополнительные фотографий</label>
                            <div class="col-lg-10">
                                <input type="file" name="photoAll[]" accept="image/*" multiple="multiple">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

<?php
echo $this->form()->closeTag();
?>

<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
<script>
    //CKEDITOR.replace("description_ru");
    //CKEDITOR.replace("description_info_product_ru");
    /*CKEDITOR.replace("description_info_quality_ru");
    CKEDITOR.replace("description_packaging_ru");
    CKEDITOR.replace("description_manual_ru");*/
</script>
