<!--a href="/admin/add/">Добавить нового пользователя</a-->
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>


<div class="col-md-12">

    <a href="<?=$this->url('admin/default', array('controller' => 'album', 'action' => 'add'));?>" class="btn btn-success">Add Album</a>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Status</th>
            <!--th>Photo</th-->
        </tr>
        </thead>
        <tbody>
        <?php foreach($album as $item){ ?>
            <tr class="active">
                <td style="width: 10px;"><?=$item->getId() ?></td>
                <td><?=$item->getName() ?></td>
                <td>
                    <?= $item->getStatus() == 1 ? '<i class="glyphicon glyphicon-ok green"></i>' : '<i class="glyphicon glyphicon-remove red"></i>' ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'album', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'album', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <?php

    echo $this->paginationControl($album,
        'Sliding',
        'pagination_control', array('route' => $this->url('admin/default', array('controller' => 'album'))));

    ?>
</div>