<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="bs-docs-section">
    <div class="well" style="color: #000000">


        <?php
        $auth = $this->identity();

        if(empty($auth)){
            $form->setAttribute('action', '/admin/auth/');
            $form->prepare();

            echo $this->form()->openTag($form);
            echo '<h1>Авторизация</h1>';
            if($mess != '')
                echo $mess;
            foreach ($form as $element){
                echo '<div class="form-group">';
                $attributes = $element->getAttributes();

                if($element->getLabel()){
                    $element->setLabelAttributes(array('class' => 'col-lg-1 control-label'));
                    if(isset($attributes['required'])){
                        $element->setLabel($element->getLabel() . ' *');
                    }
                }

                if(isset($attributes['type']) && $attributes['type'] == 'text')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-2">';
                    echo $this->formInput($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'textatea')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-2">';
                    echo $this->formTextArea($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'file')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-2">';
                    echo $this->formFile($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'select')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-2">';
                    echo $this->formSelect($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'password')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-2">';
                    echo $this->formPassword($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'submit')
                {
                    echo '<div class="col-lg-2">';
                    echo '<input type="submit" name="submit" id="btn_submit" class="btn btn-primary" value="Войти">';
                    echo '</div>';
                }
                else
                {
                    echo '<div class="col-lg-2">';
                    echo $this->formRow($element);
                    echo '</div>';
                }

                echo '</div>';
            }
            //echo '</fieldset>';
            echo $this->form()->closeTag();
            ?>
            <!--br><a href="<?php echo $this->url('auth', array('controller' => 'index', 'action' => 'register'));?>"><?php echo 'Регистрация'; ?></a-->
        <?php
        }else{
            echo 'Авторизирован как '. $this->escapeHtml($auth->getLogin());
            ?>
            <br><a href="<?php echo $this->url('auth', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo 'Выход'; ?></a>
        <?php } ?>

    </div>
</div>

