<div class="col-md-12">
    <form action="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'edit-product', 'id' => $id));?>" method="post" enctype="multipart/form-data">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <td class="text-center">Изображение</td>
                    <td class="text-left">Наименование товара</td>
                    <td class="text-left">Модель</td>
                    <td class="text-left">Кол-во</td>
                    <td class="text-right">Цена за шт.</td>
                    <td class="text-right">Всего</td>
                </tr>
                </thead>
                <tbody>
                <?php echo $cart ?>
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-8">
                <table class="table table-bordered">
                    <tbody>
                    <!--tr>
                        <td class="text-right"><strong>Предварительная стоимость:</strong></td>
                        <td class="text-right">$17.40</td>
                    </tr>
                    <tr>
                        <td class="text-right"><strong>НДС (20%):</strong></td>
                        <td class="text-right">$3.48</td>
                    </tr>
                    <tr>
                        <td class="text-right"><strong>Экологический налог (-2.00):</strong></td>
                        <td class="text-right">$0.03</td>
                    </tr-->
                    <tr>
                        <td class="text-right"><strong>Итого:</strong></td>
                        <td class="text-right">$<?php echo $price ?> </td>
                    </tr>
                    </tbody>
                </table>
                <div class="pull-right">
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'order'));?>" class="btn btn-primary">Сохранить</a>
                </div>
            </div>
        </div>
    </form>
</div>