<div class="col-md-12">
    <table class="table table-hover">
        <thead>
        <tr>
            <th></th>
            <th>Text</th>
        </tr>
        </thead>
        <tbody>
        <tr class="active">
            <td>Id order</td>
            <td><?php echo $order->getId() ?></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><?php echo $order->getFirstname() . ' ' . $order->getLastname() ?></td>
        </tr>
        <tr>
            <td>E-Mail</td>
            <td><?php echo $order->getEmail() ?></td>
        </tr>
        <tr>
            <td>Phone</td>
            <td><?php echo $order->getPhone() ?></td>
        </tr>
        <tr>
            <td>Fax</td>
            <td><?php echo $order->getFax() ?></td>
        </tr>
        <tr>
            <td>Status</td>
            <td><?php echo $order->getStatus() ?></td>
        </tr>
        <tr>
            <td>Payment</td>
            <td><?php echo $order->getPayment() ?></td>
        </tr>
        <tr>
            <td>Delivery</td>
            <td><?php echo $order->getDelivery() ?></td>
        </tr>
        <tr>
            <td>Address Payment</td>
            <td><?php echo $order->getAddressPayment() ?></td>
        </tr>
        <tr>
            <td>Address Delivery</td>
            <td><?php echo $order->getAddressDelivery() ?></td>
        </tr>
        <tr>
            <td>Comment</td>
            <td><?php echo $order->getComment() ?></td>
        </tr>
        <tr>
            <td>Date</td>
            <td><?php echo date('d.m.Y', $order->getDate()) ?></td>
        </tr>
        </tbody>
    </table>
    <div class="table-responsive">
        <table class="table table-bordered table-hover cl">
            <thead>
            <tr>
                <td class="text-left">Наименование товара</td>
                <td class="text-left">Модель</td>
                <td class="text-right">Кол-во</td>
                <td class="text-right">Цена за шт.</td>
                <td class="text-right">Всего</td>
            </tr>
            </thead>
            <tbody>
            <?php echo $product ?>
            </tbody>
            <tfoot>
            <!--tr>
                <td colspan="4" class="text-right"><strong>Предварительная стоимость:</strong></td>
                <td class="text-right">$17.40</td>
            </tr>
            <tr>
                <td colspan="4" class="text-right"><strong>Фиксированная стоимость доставки:</strong></td>
                <td class="text-right">$0.09</td>
            </tr-->
            <tr>
                <td colspan="4" class="text-right"><strong>Итого:</strong></td>
                <td class="text-right">$<?php echo $price_all ?> </td>
            </tr>
            </tfoot>
        </table>
    </div>
    <div style="text-align: right">
        <a href="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'edit', 'id' =>  $order->getId()));?>" class="btn btn-primary btn-lg">Edit</a>
        <a href="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'remove', 'id' =>  $order->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-lg">Delete</a>
    </div>
</div>