<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- <meta name="apple-mobile-web-app-capable" content="yes" /> -->

    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta() ?>

    <!-- <link rel="stylesheet" href="css/simplePagination.css"> -->

</head>

<body>



<?php echo $this->content; ?>



<footer>
    <div class="container">

    </div>
</footer>


</body>
</html>
