<!--a href="/admin/add/">Добавить нового пользователя</a-->
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<?php

?>

<div class="col-md-12">
    <?php if(!empty($orders) OR !empty($orders) OR !empty($products)){ if(!empty($orders)){ ?>
    <h2>Новые заказы</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>id order</th>
            <th>Buyer</th>
            <th>Status</th>
            <th>Price</th>
            <th>Date added</th>
            <th>Function</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($orders as $item){ ?>
            <tr class="active">
                <td style="width: 10px;"><?php echo $item->getId() ?></td>
                <td><?php echo $item->getFirstname() . ' ' . $item->getLastname() ?></td>
                <td><?php echo $item->getStatus() ?></td>
                <td>
                    <?php
                    $price = 0;
                    foreach(explode('};', $item->getProduct()) as $item_p){
                        $mas = explode(';', $item_p);
                        $price += $mas[1]*$mas[2];
                    }
                    echo "$".$price;
                    ?>
                </td>
                <td><?php echo date("d.m.Y", $item->getDate()) ?></td>
                <td>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'look', 'id' =>  $item->getId()));?>" class="btn btn-success btn-xs">Look</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php } if(!empty($comments)){ ?>
    <h2>Новые коментарий(отзывы)</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Product</th>
            <th>Status</th>
            <th>Name</th>
            <th>Comment</th>
            <th>Rating</th>
            <th>Date</th>
            <th style="width: 110px;">Function</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($comments as $item){ ?>
            <tr class="active">
                <td style="width: 10px;"><?php echo $item->getId() ?></td>
                <td>
                    <a href="<?php if($item->getProductId() != 0) echo $this->url('main', array('controller' => 'index', 'action' => 'product', 'id' =>  $item->getProductId())); else echo '#'?>" class="btn btn-success btn-xs"><?php if($item->getProductId() != 0) echo 'Open product'; else echo 'Отзыв'; ?></a>
                </td>
                <td>
                    <?php echo $status = $item->getStatus() == 1 ? '<i class="glyphicon glyphicon-ok green"></i>' : '<i class="glyphicon glyphicon-remove red"></i>' ?>
                </td>
                <td><?php echo $item->getName() ?></td>
                <td><?php echo mb_substr($item->getDescription(), 0, 100, 'UTF-8').'..'?></td>
                <td><?php echo $item->getRating() ?></td>
                <td><?php echo date("d.m.Y", $item->getDate()) ?></td>
                <td>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php } if(!empty($products)){ ?>
    <h2>Товар который заканчиваеться</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Model</th>
            <th>Price</th>
            <!--th>Category</th-->
            <th>Amount</th>
            <th>Status</th>
            <th>Function</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($products as $item){ ?>
            <tr class="active">
                <td style="width: 10px;"><?php echo $item->getId() ?></td>
                <td>
                    <img src="<?php echo $item->getPhoto() == '' ? '/images/product.gif' : '/uploads/product/'.$item->getPhoto();?>" alt="<?php echo $item->getName();?>" title="<?php echo $item->getName();?>" class="img-product-50">
                </td>
                <td><?php echo $item->getName() ?></td>
                <td><?php echo $item->getModel() ?></td>
                <td>$<?php echo $item->getPrice() ?></td>
                <!--td><?php echo $item->getCategory() ?></td-->
                <td><?php echo $item->getAmount() ?></td>
                <td>
                    <?php echo $status = $item->getStatus() == 1 ? '<i class="glyphicon glyphicon-ok green"></i>' : '<i class="glyphicon glyphicon-remove red"></i>' ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php }}else{ echo '<h2>Сейчас здесь пусто. Возвращайтесь позже.</h2>'; } ?>
</div>