<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<div class="col-md-12">
    <div id="save">
        <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'add'));?>" class="btn btn-success">Add product</a>

    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Model</th>
            <th>Price</th>
            <!--th>Category</th-->
            <th>Amount</th>
            <th>Status</th>
            <th>Function</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($products as $item){ ?>
            <tr class="active">
                <td style="width: 10px;"><?php echo $item->getId() ?></td>
                <td>
                    <img src="<?php echo $item->getPhoto() == '' ? '/images/product.gif' : '/uploads/product/'.$item->getPhoto();?>" alt="<?php echo $item->getName();?>" title="<?php echo $item->getName();?>" class="img-product-50">
                </td>
                <td><?=$item->getName() ?></td>
                <td><?=$item->getModel() ?></td>
                <td>$<?=$item->getPrice() ?></td>
                <!--td><?=$item->getCategory() ?></td-->
                <td><?=$item->getAmount() ?></td>
                <td>
                    <?php echo $status = $item->getStatus() == 1 ? '<i class="glyphicon glyphicon-ok green"></i>' : '<i class="glyphicon glyphicon-remove red"></i>' ?>
                </td>
                <td>
                    <!-- <a href="<?=$this->url('admin/default', array('controller' => 'product', 'action' => 'add-size', 'id' =>  $item->getId()));?>" class="btn btn-warning btn-xs">Add size</a> -->
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'product', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php

    echo $this->paginationControl($products,
        'Sliding',
        'pagination_control', array('route' => $this->url('admin/default', array('controller' => 'product'))));

    ?>
</div>


<script>
    function httpGet(theUrl)
    {
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.open( "GET", theUrl, false ); // false for synchronous request
        xmlHttp.send( null );
        return xmlHttp.responseText;
    }

    var x = new XMLHttpRequest();
    x.open("GET", "/cron/countProduct/", true);
    x.onload = function (){
         x.responseText;
    }
    x.send(null);
</script>