<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul></ul>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<div class="col-md-12">
    <div id="save">
        <!--a href="<?php echo $this->url('admin/default', array('controller' => 'order', 'action' => 'add'));?>" class="btn btn-success">Add order</a-->

    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Product</th>
            <th>Status</th>
            <th>Name</th>
            <th>Comment</th>
            <th>Rating</th>
            <th>Date</th>
            <th style="width: 100px;">Function</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($comments as $item){ ?>
            <tr class="active">
                <td style="width: 10px;"><?php echo $item->getId() ?></td>
                <td>
                    <a href="<?php if($item->getProductId() != 0) echo $this->url('main', array('controller' => 'index', 'action' => 'product', 'id' =>  $item->getProductId())); else echo '#'?>" class="btn btn-success btn-xs"><?php if($item->getProductId() != 0) echo 'Open product'; else echo 'Отзыв'; ?></a>
                </td>
                <td>
                    <?php echo $status = $item->getStatus() == 1 ? '<i class="glyphicon glyphicon-ok green"></i>' : '<i class="glyphicon glyphicon-remove red"></i>' ?>
                </td>
                <td><?php echo $item->getName() ?></td>
                <td><?php echo mb_substr($item->getDescription(), 0, 100, 'UTF-8').'..'?></td>
                <td><?php echo $item->getRating() ?></td>
                <td><?php echo date("d.m.Y", $item->getDate()) ?></td>
                <td>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'edit', 'id' =>  $item->getId()));?>" class="btn btn-primary btn-xs">Edit</a>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'remove', 'id' =>  $item->getId()));?>" onclick="return confirm('Удалить запись?');" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php

    echo $this->paginationControl($comments,
        'Sliding',
        'pagination_control', array('route' => $this->url('admin/default', array('controller' => 'comment'))));

    ?>
</div>